labgem/PPanGGOLiN

ppanggolin/ppanggolin.py

Fixes #2.  Changed __load_gff function to allow Refseq gffs to be read, and to allow reading gffs with pseudogenes without trying to add the pseudogenes to the pangenome.

Loading Refseq GFFs. 

---

ppanggolin/command_line.py
ppanggolin/ppanggolin.py

Saving NEM output files in the given output directory when using -kf.
Creating new NEM "summary" files to deal with chunks when the number of organisms is above the number specified in -ck. Might be erroneous as there is no apparent way to garantee that "shell" partitions are ordered the same way between chunks.
Using -uf /former/nem/output/dir , ppanggolin will use the output parameters from NEM for each organism that was present in the precedent partitionning, to help NEM and speed things up.

Adding options to use partitionning from a former run of ppanggolin to initialize NEM

---

tests/region/test_Region.py

Tests for Region class updated.  
I did not do fully getBorderingGenes because I have some difficulty to understand its purpose.

Hack20 test region

---

docs/user/Outputs.md

Correct argument name for computing genome fluidity in the metrics command

Fix metrics documentation

---

setup.py

Force to use cython<3.0.0 to prevent install crash in macOS install

Force to use cython<3.0.0 to prevent crash in macOS install

---

ppanggolin/formats/writeFlatPangenome.py

In the current dev version, generating the GEXF graph file take longer compared to last stable version 1.2.105. This delay is caused by the function, `metadata_sources`, being repeatedly called within loops. This function parsed all metadata each time it ran.
To fix this, I moved the function call outside the loops. 
As a result, the graph generation speed is now back to its previous performance level. :tada: 
I also fix `.gz` extension being added twice to the output gexf file when the flag `--compress` is used.

Improved GEXF Graph File Generation Speed

---

.github/workflows/check_doc.yml
.readthedocs.yaml
docs/Makefile
docs/api/api_ref.md
docs/api/indice_and_table.md
docs/api/modules.md
docs/api/ppanggolin.formats.md
docs/index.md
docs/requirements.txt
pyproject.toml

The API reference generated by sphinx-apidoc was missing in our ReadTheDocs-hosted documentation. This problem occurred because ppanggolin and all Python dependencies weren't installed during the documentation build process. For more details, refer to this [Stack Overflow](https://stackoverflow.com/questions/64697264/genindex-and-modindex-footer-links-dont-work-in-readthedocs-io).
To fix the problem:
- Added all Python dependencies in a specific category within the toml file.
- Modified the installation process in `.readthedocs.yaml`  to install ppanggolin with the documentation and Python dependencies.
- Remove requirements.txt in docs folder as it was not used anymore
- Added the API Reference to the TOC tree of the Dev documentation section.

Fix api reference in readthedoc

---

ppanggolin/formats/readBinaries.py
ppanggolin/pangenome.py
ppanggolin/utils.py

**Overview:**
Version 2 introduces changes that break the compatibility with pangenome files created using Version 1. 
This PR addresses the check of the PPanGGOLiN versions that have been used to create the pangenome file and the current version that parses this file. 🛠️
**Error Handling:**
1. **Scenario 1 (Incompatibility):**
- When the installed PPanGGOLiN version is >= 2 and the pangenome file was created by a version < 2:
PPanGGOLiN will fail and raise the following error:
`ValueError: The provided pangenome file was created by PPanGGOLiN version 1.2.105, which is incompatible with the current PPanGGOLiN version 2.0.0a1.`
2. **Scenario 2 (Version Mismatch):**
- In any other case where the major version between the pangenome file and the current installation differs:
The following …

Add version check between pangenome file (h5) and the installed ppanggolin

---

docs/dev/buildDoc.md
docs/user/install.md

This Pull Request addresses recent changes in the repository to ensure alignment with the updated structure of the repo.
1. The `requirements.txt` file in the `docs` folder has been removed. Documentation dependencies are now only specified in the `pyproject.toml` file, categorized as optional dependencies under the name `docs`. Previously, the `docs/requirements.txt` file was used by readthedocs for building the documentation. However, the `.readthedocs.yaml` file has been modified in PR #156 to only rely on dependencies listed in `pyproject.toml`. The documentation has been updated accordingly. 
2. The manual installation process for PPanGGOLiN included a list of Python dependencies to be placed in a `requirements.txt` file. These dependencies are now defined in the `pyproject.toml` …

Update install documentation

---

pyproject.toml

Update readthedocs-sphinx-search version to address a security vulnerability.
See here for more info on the security vulnerability: https://github.com/readthedocs/readthedocs-sphinx-search/security/advisories/GHSA-xgfm-fjx6-62mj

Update  readthedocs-sphinx-search version

---

ppanggolin/cluster/cluster.py
ppanggolin/workflow/all.py

Subject: PR: Unique tmpdir Names for Clustering
Previously, temporaty directory names in the clustering step were based on the date and hour, like `/tmp/clustering_tmpdir_2024-02-12_11.02.20/`. This caused problems when PPanGGOLiN ran simultaneously (in a pipeline for example), potentially creating the same tmpdir for different executions and causing errors.
To fix this, I just added the Process ID (PID) to the tmpdir name. Now, each tmpdir is unique, avoiding conflicts.
Additionally, I noticed and fixed a small bug: the keep_tmp_files argument was missing from the clustering function in workflow mode. This made it impossible to save tmpdir with a config file in a workflow.

Making tmpdir name truly unique in clustering step

---

ppanggolin/figures/draw_spot.py

This pull request addresses an issue in the HTML spots plot.
The radio buttons, which are intended to modify the color of genes, were not functioning as expected. This issue is likely a result of modifications made to the script during the update of the Bokeh dependency to version 3.
Additionally, I have removed the width=200 and height=100 arguments from the Div function in the title of the radio button to avoid creating excessive space between the title and the buttons.

Fixing spot plot

---

.github/workflows/main.yml
ppanggolin/formats/writeSequences.py
ppanggolin/geneFamily.py

This pull request addresses an issue with the `ppanggolin fasta` command, specifically when attempting to output core, softcore and rgp protein families (refer to #179).
The problem stemmed from the fact that annotation data from the pangenome.h5 file was not loaded when writing protein families, even though it is crucial for determining whether a family belongs to the core or not.
Additionally, I identified a problem with module filtering. It was not possible to write genes, protein families, or gene families of a module when giving a module id because argparse expected a regex pattern while it was processing string. To fix this, I added a type function to validate the input value that use the regex to validate module format.
I also incorporated some `ppanggolin fasta`  commands into the …

 Fixing Issues in ppanggolin Fasta Command

---

ppanggolin/formats/writeBinaries.py

Small bug detected when no module is predicted, there is a DivisionbyZero error when calculating module info and writing it to the pangenome file.
Not having a module is quite rare, but it can happen and should be handled. To fix the problem, I simply added a test to prevent the division.
The error:
```
Traceback (most recent call last):
File "/usr/local/bin/ppanggolin", line 10, in <module>
sys.exit(main())
File "/usr/local/lib/python3.10/site-packages/ppanggolin/main.py", line 219, in main
ppanggolin.workflow.all.launch(args)
File "/usr/local/lib/python3.10/site-packages/ppanggolin/workflow/all.py", line 288, in launch
launch_workflow(args, panrgp=True, panmodule=True)
File "/usr/local/lib/python3.10/site-packages/ppanggolin/workflow/all.py", line 164, in launch_workflow …
```

Fix zero div when there is no module

---

ppanggolin/annotate/annotate.py
ppanggolin/annotate/synta.py
ppanggolin/meta/meta.py
ppanggolin/utils.py

This PR does: 
- Improve error message to provide clearer user guidance when input files differ from expected formats (see issue #185).
- Added a regex check for the first line of GFF files to increase flexibility. Now any file starting with `##gff-version<whitespace>3` is recognized as a GFF file.
- Fixed a pandas warning in ppanggolin/meta/meta.py (line 80) related to the deprecated 'errors='ignore'' parameter. The warning occurred when adding metadata. The problem stemmed from an unnecessary check in the function used to validate the input metadata. The conversion of a Pandas DataFrame column with an object type to an integer with ignored errors was found to be redundant and incorrectly implemented as the transformed column was not used. Therefore, we decided to remove this line for …

Improve error message when parsing input files

---

.github/workflows/main.yml
ppanggolin/formats/writeFlatGenomes.py
ppanggolin/formats/write_proksee.py

Context:
A single element of the pangenome may contain multiple metadata entries. When these metadata entries are presented in formats such as GFF or proksee, different values are concatenated using a pipe symbol. In cases where a pipe symbol exists within a metadata value, an error is thrown prompting the user to specify an alternative delimiter using the `--metadata_sep` parameter.
Problem:
Previously, the `metadata_sep` parameter was only considered in GFF output and was not implemented in proksee output. This resulted in errors when requesting metadata with pipe symbols in the values. And the `--metadata_sep` was not initialized correctly when gff output was not specified.
Solution:
To address this issue, the `metadata_sep` parameter has now been implemented in the proksee output code …

Fix missing metadata sep when using metadata in proksee

---

docs/index.md
docs/user/writeFasta.md

As mentioned in this issue #191, the documentation for the `fasta` command is missing in version 2 documentation hosted on read the doc. 
This PR adds that documentation. :v:

add missing fasta cmd documentation

---

ppanggolin/projection/projection.py

This PR fixes the bug reported in #207.
In the projection command using a gbff file as input genome, the input genes weren't linked to any gene families, resulting in all genes being without a pangenome family. This was due to a mismatch between ppanggolin's internal IDs and the original IDs from the GBFF file.
When gene IDs are unique across input genomes, the original ID (local_identifier) should be used instead of the PPanGGOLiN-generated IDs. However, this replacement wasn't happening because of a flaw in the iterator management, which left it empty.
The iterator has been properly fixed, resolving the issue.

Fix gene ID mismatch in projection command

---

ppanggolin/projection/projection.py

This PR fixes a rare problem with the spot prediction of the projection command. 
In projection, we reproduce the spot graph and check that the original RGPs are in their spots. Then, from this spot graph, we add the new RGPs and find their spots. 
In the pangenome of GTDB species HIMB11 sp003486095 (built with 20 genomes), I found an RGP that initially had no spot, which is included in the spot graph recreated by projection.
It turns out that its right border had a gene from a family that was initially considered multigenic, but that this family became non-multigenic in the projection thanks to the addition of the projected genome in the family statistics. 
Normally, the projected genome shouldn't be taken into account when rebuilding the spot graph. 
To fix this problem, multigenic …

Fix spot prediction in projection command

---

ppanggolin/projection/projection.py
ppanggolin/region.py

This PR fixes another rare issue with the projection command's spot prediction.
In the projection, we reproduce the spot graph and check that the original RGPs are in their spots. Then we add the new RGPs from this spot graph and find their spots. In some cases, a new RGP may be connected to two spots (technically, the RGP in the graph is connected to two connected components). If the projected genome was first used in the pangenome, these two spots would be a unique spot. 
The choice made in the projection command is not to change the previous spot result, but simply to report the two spots for this particular RGP in the output of the projection. 
This situation was initially handled.  Reporting multiple spots in the projection output is enabled and works fine. But the spot class has …

Handle multiple spots per RGP in projection command

---

ppanggolin/cluster/cluster.py

When running ppanggolin on a large collection of genomes, the temporary file generated by the clustering step can become very large. For instance, when constructing a pangenome of E. coli made of ~33k genomes, the temporary directory was 404GB in size. This size can quickly become a bottleneck and may exceed the capacity of the temporary directory.
This large temporary file is primarily caused by the duplication of CDS sequences from all genomes in the temporary directory. Initially, ppanggolin writes these sequences to the temporary directory, and then mmseqs copies them to create its database file.
To address this issue, the solution implemented in this PR is to use the `createdb-mode 1` option of mmseqs `createdb` command. This option enables mmseqs to utilize symbolic links instead of …

Use mmseqs createdb-mode 1 to reduce clustering tmpdir size

---

.github/workflows/check_recipes.yml
.github/workflows/main.yml

This PR is for fixing the macOS github runner which crashed due to github actions "macos-latest" moving to macos-14 with runners with oxs-arm64 architecture, which is not currently supported in bioconda.

Fix mac recipe

---

.github/workflows/check_doc.yml
.github/workflows/main.yml
docs/dev/contribute.md
ppanggolin/cluster/cluster.py
ppanggolin/formats/writeFlatPangenome.py
ppanggolin/formats/write_proksee.py
testingDataset/compare_results.py
testingDataset/expected_info_files/myannopang_info.yaml
testingDataset/expected_info_files/mybasicpangenome_info.yaml
testingDataset/expected_info_files/stepbystep_info.yaml
testingDataset/launch_test_locally.py

PPanGGOLiN  has a CI that tests most of its commands and parameters to make sure that none are broken. However, it does not test the content of the file created by the command. This means that if a change in the code affects the content of an output, we may not see it.
To mitigate this risk, this PR introduces a minimal check on the output files produced by the `ppanggolin info' command to ensure that no changes have been made to the contents of the pangenome. 
- The CI pipeline now includes a call to a Python script named `compare_results.py`, located within the `testingDataset` directory. This script compares the content of the files produced by the CI with the expected files stored in the `testingDataset/expected_info_files` directory. 
- A companion script named …

Test ppanggolin outputs consistency 

---

.github/workflows/main.yml
testingDataset/launch_test_locally.py

This PR implements two adjustments to speed up the GitHub CI process:
1. It utilizes multiple CPUs instead of just one. The number of available cores is assessed and utilized in ppanggolin commands that support multiprocessing. GitHub runners typically have 4 CPUs available. You can find more information about runner resources in [GitHub's documentation](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories).
2. It limits testing to only the oldest and latest supported Python versions, rather than testing on all versions. While this change may not necessarily reduce the overall workflow duration, it significantly reduces computational load per execution. 
These …

Make github CI workflow faster

---

.github/workflows/main.yml
ppanggolin/RGP/genomicIsland.py
ppanggolin/annotate/annotate.py

This PR fixes two related problems:
- read "Is_circular" properly from gff files. They were not read as they should've and this attribute was ignored previously.
- Force the RGP "looping" around circular contigs in the specific case where a contig does not have a single node at score 0. Previously the looping was not done in that case, and scores were not recomputed with the information of circularity.

Fix rgp circularity

---

docs/user/projection.md
ppanggolin/align/alignOnPang.py

This fixes #221.
The previous version was writing all genes of all input genomes used in the projection, then the genes from the input genome that did not have a gene family in the pangenome.
Correct behavior is to only write the genes of the input genome.

Fix 'gene_to_gene_family.tsv' file from projection

---

.github/workflows/main.yml
docs/user/metadata.md
docs/user/writeGenomes.md
ppanggolin/__init__.py
ppanggolin/annotate/annotate.py
ppanggolin/formats/__init__.py
ppanggolin/formats/readBinaries.py
ppanggolin/formats/writeFlatMetadata.py
ppanggolin/formats/write_proksee.py
ppanggolin/geneFamily.py
ppanggolin/main.py
ppanggolin/meta/meta.py
ppanggolin/metadata.py
ppanggolin/pangenome.py
testingDataset/expected_info_files/myannopang_info.yaml
testingDataset/launch_test_locally.py
tests/annotate/test_annotate.py

This PR extracts information from annotation files (GBFF and GFF) and adds them as metadata to genomes and contigs in the pangenome file.
Tasks to complete:
I have completely redesigned the `read_org_gbff` function to simplify metadata extraction from GBFF files.
Metadata will still no be displayed in output files by default as this behavior may lead to some error regarding the metadata separator. If the user want to display metadata in the output files, it needs to add the `--add_metadata` flag as before. 
Note: This PR builds on the AnnotJoin branch, which has introduced several changes to annotation file parsing. Therefore, it is dependent on PR #206 and should be merged afterward.

Add metadata from annotation files

---

ppanggolin/annotate/annotate.py
ppanggolin/projection/projection.py
ppanggolin/workflow/all.py

This PR implements the use of the genetic_code input parameter (defaults to 11) when reading from a GBFF or GFF file in cases where the /transl_table attribute is missing. When translation table information is missing, the value provided by the translation_table argument is used, which defaults to 11 but can be adjusted by the user if necessary.
Previously, missing transl_table in GBFF files was not handled, resulting in errors (see issue #226). In addition, the translation code in GBFF files was hardcoded to 11 and could not be changed.
This update should fix issue #226.

Improve reading from custom gbff files

---

ppanggolin/formats/writeMSA.py
testingDataset/compare_results.py
testingDataset/launch_test_locally.py

As highlighted in issue #223, the default value of `dup_margin` in the function [is_single_copy](https://github.com/labgem/PPanGGOLiN/blob/f3ba6a1f33256f19175b570c4b711bb8970d0365/ppanggolin/formats/writeMSA.py#L25) was incorrect and should be 0.05. However, this had no practical impact as the default value was never actually used.
This PR removes the `is_single_copy` function and replaces it with the `is_single_copy` method from the `Gene_Family` class, which is already utilized elsewhere in the code. This change reduces code duplication and ensures consistency across the codebase.
This update addresses the concerns raised in issue #223.

Fix dup margin default value

---

ppanggolin/formats/writeFlatPangenome.py

The `spot_modules.tsv` output file, which maps spots to modules, is always empty even when there are modules with included spots.
This issue was caused by a refactoring in the `Module` class, which made the module attributes iterable, causing a comparison in the `write_spot_modules` function to always return false.

Resolve empty `spot_modules.tsv` output file

---

ppanggolin/annotate/annotate.py
ppanggolin/formats/readBinaries.py
ppanggolin/formats/writeFlatMetadata.py
ppanggolin/formats/writeMetadata.py
ppanggolin/meta/meta.py
ppanggolin/metadata.py
ppanggolin/pangenome.py
tests/test_metadata.py
tests/test_pangenome.py

In pangenome, an element (gene, family, ...) could be associated with multiple metadata for one source. 
A metadata identifier has been added to each metadata. The identifier is object-dependent and aims to identify the right metadata for each object in cross-reference.

Adding identifier to metadata in object and HDF5

---

ppanggolin/align/alignOnPang.py
ppanggolin/cluster/cluster.py
ppanggolin/formats/writeMSA.py
ppanggolin/formats/writeSequences.py
ppanggolin/utils.py

PPanGGOLiN manages sub-processes between scripts in different ways. A function has been created that takes the command line and launches the process. 
The function also handles standard and error output to make execution more informative and easier to debug.

Make subprocess more detailed with info and error message

---

.github/workflows/main.yml
docs/user/PangenomeAnalyses/pangenomeCluster.md
ppanggolin/cluster/cluster.py
ppanggolin/formats/writeFlatPangenome.py
ppanggolin/geneFamily.py
ppanggolin/genome.py
ppanggolin/workflow/all.py

When external clustering is provided, gene families sequences were missing  in the pangenome file. This resulted in some output files being impossible to generated. We especially noticed that the FASTA file of RGP borders (created by `ppanggolin write_pangenome --borders`) was containing only sequence IDs without actual sequences.
This PR adds functionality to translate the representative gene of each gene family in the cluster step, enabling the writing of the protein sequence into the HDF5 pangenome file.
This change should resolve the issue of missing sequence outputs.

Add the protein sequence to gene family when reading clustering

---

docs/user/RGP/rgpOutputs.md
ppanggolin/formats/writeFlatPangenome.py
ppanggolin/region.py
ppanggolin/utils.py
ppanggolin/workflow/all.py

The option `--infer_singleton` was unavailable in the workflow commands, but only with a configuration file. It's now possible to use the option directly in a workflow command. 
Also, we add the name of the start and stop gene, the coordinates and the length of the gene in the `region_of_plasticity.tsv` file.

Add infer singleton option in workflow and add gene information in RGP output

---

ppanggolin/annotate/synta.py
ppanggolin/formats/readBinaries.py
ppanggolin/genome.py
tests/context/test_context.py
tests/test_pangenome.py
tests/test_region.py

In rare cases, Aragorn predicts RNA genes with negative coordinates. 
For example, in contig `NZ_CSQN01000072`, it predicts the following tRNA:
```
>NZ_CSQN01000072.1
1 gene found
1   tRNA-Ile                      c[-3,86]	34  	(gat)
```
Previously, start and stop positions were not validated, allowing such erroneous coordinates to persist. When written to the pangenome file, which stores coordinates as positive integers, the `-3` was converted to `4294967293`.
Now, with the updates made in the development branch (particularly in PR #206, which includes management of joined coordinates), extensive checks are performed on coordinates.
It has been decided that PPanGGOLiN should ignore genes predicted by Aragorn with invalid coordinates. tRNAs are only predicted to remove any CDS that would …

Ignoring weird tRNA from Aragorn

---

ppanggolin/RGP/rgp_cluster.py
ppanggolin/annotate/annotate.py
ppanggolin/geneFamily.py
ppanggolin/projection/projection.py
ppanggolin/region.py

This PR improves metadata management in two commands:
1. **Projection**: Previously, metadata was not included in the output file due to missing specifications when loading the pangenome. This PR resolves that issue, ensuring metadata is properly added to the output file.
2. **RGP Clustering**:
- Previously, modules information were not passed through in the graph. Now, modules found in an RGP are included in the `modules` attribute of nodes. If there are multiple modules, they are joined with a semicolon (e.g., `module_1;module18`).
- Previously, only metadata associated with RGPs was included in the RGP cluster graph. This PR now also includes metadata associated with families, spots, modules, and genes in RGP nodes. This addition is done in a concise way: the RGP node will only have …

Improve metadata management

---

ppanggolin/formats/write_proksee.py

In some cases, modules in the Proksee map were not displayed correctly. For example:
This issue arises when a gene overlaps the edge of a contig. For genes and RGPs, this scenario is handled by drawing each piece individually   (one starting at the end of the contig and the other beginning at the start of the next). However, this was not implemented for modules, leading to incorrect representations when a gene in a module was split across multiple pieces.
This PR resolves the issue by applying the same logic used for genes and RGPs to modules. Now, modules are accurately drawn even when a gene spans the edge of a contig.
In this example, a gene is overlapping the end of a circular contig. this gene belong to module 217 and this module is drawn correctly folowing the gene:

Fix proksee module

---

.github/workflows/main.yml
ppanggolin/annotate/annotate.py
ppanggolin/formats/writeBinaries.py
ppanggolin/formats/writeMetadata.py

This PR adjusts two aspects related to metadata handling:
1. Properly trims trailing quotes when ppanggolin parses multi-line features in GBFF files. Previously, these remaining quotes were incorrectly included in contig and genome metadata, and product fields of genes.
2. Addresses an issue where `None` values were being added to the metadata table when a line had no value for a specific column. Since  column needs to be  homogeneous in table of h5 file, the  `None` values caused an obscure error.

Fix metadata related issues

---

.github/workflows/main.yml
docs/user/install.md
ppanggolin/nem/rarefaction.py
ppanggolin_env.yaml

This PR is all about making PPanGGOLiN compatible with Python 3.11 and 3.12. 
Now you can use PPanGGOLiN with Python versions 3.8 through 3.12.  🎉 
1. **Compatibility Update**: Tweaked the `random.sample` call in the `rarefaction` module to fix issues with the newer Python versions. This problem was pointed out in issue #253.
2. **Docs Update**: Updated the installation doc to indicate that we support Python 3.8, 3.9, 3.10, 3.11, and 3.12.

Add support for python 3.11 and 3.12

---

ppanggolin/annotate/synta.py

This PR addresses an issue reported in the issue #254 where genes predicted by Aragorn exceed the contig length. 
This is done by identifying and this the genes when parsing Aragorn results when they exceed the contig length. Gene with negative coordinates predicted from Aragorn were already handle with the same startegy. (This has been added in PR #245).
The Genbank assembly GCA_020692865 had this issue so we can use it to reproduce the error.
1. Download GCA_020692865 genome and create the input file for PPanGGOLiN:
```bash
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/020/692/865/GCA_020692865.1_ASM2069286v1/GCA_020692865.1_ASM2069286v1_genomic.fna.gz
echo GCA_020692865.1$'\t'GCA_020692865.1_ASM2069286v1_genomic.fna.gz > accession_to_fna_genome_path_GCA_020692865.tsv
```
2. Launch …

Handle Aragorn gene that exceed contig length

---

ppanggolin/formats/writeFlatPangenome.py
ppanggolin/projection/projection.py
ppanggolin/utils.py
ppanggolin/workflow/all.py

**Summary**
This PR addresses an issue with the default behavior of flat output file generation in workflow commands when specified through the configuration file.
**Background**
In the commands `write_pangenome`, `write_genome`, and `draw`, the default setting for output files is `false`, requiring users to explicitly specify the desired files via the command line. However, within workflow commands, these outputs are generated by default unless the `--no_flat_files` parameter is used. The intended behavior was to force output files to be generated by default unless overridden by the configuration file or CLI arguments.
**Issue**
The previous implementation incorrectly forced output file generation even when the configuration file specified `false` for certain outputs. This made it …

Fix config outputs in workflow commands when set in config file

---

ppanggolin/projection/projection.py

An edge case have been identified in issue #264 where a pangenome without any existing spots is used in a projection. In this case, the projection process, which predicts spots in the input genome, attempts to retrieve the highest spot ID to determine the appropriate ID for any new spots detected. This leads to an error when no spot IDs are available.
To resolve this, I’ve implemented a check to see if the pangenome contains any spots. If no spots are found, the process will now default to using an ID of 1 for new spots.

Handle case where a spotless pangenome is used in projection

---

ppanggolin/RGP/rgp_cluster.py
ppanggolin/annotate/annotate.py
ppanggolin/annotate/synta.py
ppanggolin/cluster/cluster.py
ppanggolin/context/searchGeneContext.py
ppanggolin/figures/draw_spot.py
ppanggolin/formats/writeAnnotations.py
ppanggolin/formats/writeBinaries.py
ppanggolin/formats/writeFlatGenomes.py
ppanggolin/formats/writeFlatPangenome.py
ppanggolin/formats/writeMSA.py
ppanggolin/formats/writeMetadata.py
ppanggolin/geneFamily.py
ppanggolin/genome.py
ppanggolin/metadata.py
ppanggolin/mod/module.py
ppanggolin/nem/NEM/nem_alg.c
ppanggolin/nem/NEM/nem_hlp.c
ppanggolin/nem/NEM/nem_typ.h
ppanggolin/nem/partition.py
ppanggolin/nem/rarefaction.py
ppanggolin/pangenome.py
ppanggolin/projection/projection.py
ppanggolin/region.py
ppanggolin/utility/utils.py
ppanggolin/utils.py

:fr:
typos dans le code source, aussi trouvées avec codespell
:us: 
This has been done with codespell 2.3.0 with a command like looking like this
`codespell -L=comma,separated,excluded,words ppanggolin`
and then fixing by hand all typos (yes).

some typos in source

---

ppanggolin/nem/partition.py

When partition step fails as in issue #262, an error occur but in a later step and the message of the partition failure is only given as a debug log making hard for the user to understand whats going on.
Now, with this PR if the partition step fails, a warning log is thrown making what's going wrong more obvious for the user.
This is a quick fix. Ideally, PPanGGOLIN should keep running even if partitioning fails, since it can still provide useful data like core and soft genomes. Implementing this behavior would take more work.This enhancement is tracked in issue #270.

Print a warning log when partition step fails

---

ppanggolin/nem/partition.py

This PR fixes an issue in the `partition` module where the `random.sample` function caused an error in Python versions 3.11 and 3.12, as reported in issue #268.
While PR #255 added support for Python 3.12, this specific issue has been missed. The `random.sample` function is only called when the number of genomes exceeds the chunk size, which defaults to 500. Since the CI tests run with only 50 genomes, this bug wasn't detected.
To verify the fix, you can run the `partition` command with a chunk size smaller than the number of genomes:
```bash
cd testingDataset
ppanggolin annotate --fasta genomes.fasta.list --output stepbystep --cpu 12
ppanggolin cluster -p stepbystep/pangenome.h5 --cpu 12
ppanggolin graph -p stepbystep/pangenome.h5
ppanggolin partition --output stepbystep -f -p …
```

Fix random.sample call to be compatible with python 3.12

---

docs/user/PangenomeAnalyses/pangenomeCluster.md
docs/user/PangenomeAnalyses/pangenomeStat.md
ppanggolin/annotate/annotate.py
ppanggolin/cluster/cluster.py
ppanggolin/formats/writeFlatGenomes.py
ppanggolin/geneFamily.py
ppanggolin/genome.py
ppanggolin/pangenome.py

This PR addresses a few issues that users encountered when running the cluster command with an external cluster file.
Fixes made:
- **Avoid unnecessary gene sequence loading**: Previously, gene sequences were being requested and loaded even when using an external cluster file. This was a problem if the pangenome didn’t have sequences. 
- **Ensure correct data types for gene and family IDs**: When gene IDs were purely numeric, pandas was reading them as integers, causing mismatches since gene and family IDs should be treated as strings. We now explicitly ensure these columns are read as strings, avoiding any confusion.
- **Clear error for missing genes**: If a gene from the cluster file wasn’t found in the pangenome, the code didn’t raise an error immediately. This led to confusing errors …

Fix error when using an external clustering 

---

ppanggolin/annotate/annotate.py
ppanggolin/formats/writeMetadata.py

This PR addresses an issue where genome tags in GBFF files are empty. These tags were being included as genome metadata, but their zero length caused problems when writing to the pangenome file.
To fix this, I’ve implemented a filter to ignore any tags with empty values. Instead a debug log will now be generated to provide info into what’s being filtered out. I also improved the error message when dealing with wrong metadata.
This should resolve issue #285.
One example of an empty tag is `genome_md5`, which looks like this:
```
LOCUS       ctg.s2.38.arrow        14924 bp    DNA     linear   UNK 
DEFINITION  Fusobacterium sp. nucleatum KCOM1001
ACCESSION   ctg.s2.38.arrow
KEYWORDS    .
SOURCE      Fusobacterium sp. nucleatum KCOM1001.
ORGANISM  Fusobacterium sp. nucleatum KCOM1001 …
```

Fix empty metadata tag in annotation file

---

ppanggolin/annotate/annotate.py
ppanggolin/utils.py
tests/utils/test_utilities.py

We’ve noticed that many issues in PPanGGOLiN are caused by non-ASCII characters in the `product` field of CDS annotations. This often happens with genomes annotated by Bakta, where some COG annotations include these characters (check out the related Bakta issue [here](https://github.com/oschwengers/bakta/issues/215)).
The HDF5 tables used by PPanGGOLiN can’t handle non-ASCII characters. When these characters show up in the `product` field, they cause confusing errors and failures in the tool.
This PR fixes the problem by automatically checking for non-ASCII characters in the `product` field and replacing them with underscores (`_`). This change will help PPanGGOLiN run smoothly without errors related to non-ASCII characters.
- #95
- #175
- #222
- #233
- #252

Filter non ASCII character

---

ppanggolin/annotate/annotate.py
ppanggolin/projection/projection.py

This small PR addresses two issues:
- Changes the log level for missing translation table entries in input genome files from INFO to DEBUG to reduce log clutter when this info is absent across files.
- Fixed a missing application of the `disable_bar` flag in the projection step when using the `fast` flag. This prevent unwanted progress bars from appearing when `--disable_prog_bar` is enabled.

Adjust logging and fix unwanted progress bar

---

ppanggolin/annotate/annotate.py
ppanggolin/annotate/synta.py
ppanggolin/genome.py
ppanggolin/projection/projection.py
tests/annotate/test_annotate.py

This PR fixes the bug reported in [issue #299](https://github.com/labgem/PPanGGOLiN/issues/299).
When parsing a GFF file, the contig length is usually extracted from the line:
```
##sequence-region <contig name> 1 <end position>
```
This length is used to adjust gene coordinates that overlap the contig edge, splitting such genes into two parts to ensure they remain within the contig boundaries (as introduced in [PR #206](https://github.com/labgem/PPanGGOLiN/pull/206)).
However, this line is optional according to the [GFF3 specification](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md). As a result, when this line is missing, the contig length is undefined, causing errors during the correction of overlapping gene coordinates.
To resolve this issue, the …

Fix Contig Length Detection for GFF Parsing

---

docs/user/RGP/rgpOutputs.md
ppanggolin/formats/writeFlatPangenome.py
ppanggolin/workflow/all.py

- Add --use_pseudo option in ppanggolin all
- Add RGP score in the regions output

Edit regions output

---

ppanggolin/RGP/genomicIsland.py
ppanggolin/formats/readBinaries.py
ppanggolin/formats/writeBinaries.py
ppanggolin/region.py

Small PR following #303
- Added the RGP score to the pangenome table to include it in the RGP output file when it is produced with the `writepangenome` command.
- Changed the default RGP score from 0 to None to avoid incorrect scores in the output.
- Ensured compatibility with older pangenome files without RGP scores.

Add RGP Score to Pangenome Table

---

ppanggolin/workflow/all.py

The workflow commands incorrectly handle the argument for controlling whether spots should be drawn.  
In the `draw` command, the correct argument to enable spot drawing is `--draw_spots`. However, in the workflow code, the check to decide whether to draw spots mistakenly uses the `spots` argument instead.  
The `spots` argument is a valid parameter of the `draw` command, but it serves a different purpose: specifying which spots to draw (defaulting to all). This mismatch means it’s currently impossible to skip drawing spots unless the `--no_flat_files` option is used. As a result, users cannot selectively avoid `draw_spots` while still generating parts of the flat file output.  
This PR resolves the issue by ensuring the workflow commands use the correct `--draw_spots` argument to control …

Fix incorrect argument handling for spot drawing in workflow commands

---

ppanggolin/figures/draw_spot.py

I ran into a `RecursionError: maximum recursion depth exceeded while calling a Python object` while generating spot figures for a Listeria monocytogenes pangenome with ~2k genomes.  
This issue was already reported in issue #96 
To fix it, I’ve increased the recursion limit to twice the number of RGPs in the dendrogram. This should ensure we don’t hit the limit again, even with large pangenomes.

Increase recursion limit in draw spot to prevent error

---

.github/workflows/check_doc.yml
.readthedocs.yaml
ppanggolin_env.yaml
pyproject.toml

This PR makes the following updates:
- Moves all Python dependencies from optional to main in `pyproject.toml`.
- Enforces `numpy > 1.24` to ensure compatibility with Python 1.12.
- Ensures all sub-packages of `ppanggolin` are included during installation.

Improve python dependencies

---

.github/workflows/main.yml

Hello,
This is a draft PR to see how the arm-based CPU macOS runners do, now that bioconda supports arm64 recipes on macOS as well (so that we don't get stuck on macos-13, which is the lowest github runner version nowadays).
Will merge only if it goes well in the CI.
Adelme

Test new macos runner

---

ppanggolin/utils.py

Previously, `check_tsv_sanity` failed when given a compressed genome list file, even though compressed files were handled correctly later in the pipeline. This PR fixes that by properly supporting compressed input files from the start.  
I also cleaned up `check_tsv_sanity` by removing unnecessary try-except blocks (since they didn’t add much value) and using a context manager to ensure proper file handling.

Support compressed input files 

---

.github/workflows/black_lint.yml
ppanggolin/meta/meta.py

Declare regex pattern as a raw string to comply with Python 3.12 syntax and silence SyntaxWarning.

Fix regex warning

---

.github/workflows/black_lint.yml
ppanggolin/align/alignOnPang.py
ppanggolin/annotate/annotate.py
ppanggolin/annotate/synta.py
ppanggolin/cluster/cluster.py
ppanggolin/context/searchGeneContext.py
ppanggolin/formats/writeMSA.py
ppanggolin/formats/writeSequences.py
ppanggolin/utils.py

This PR does two things:
- Ensure external required tools are available in PATH in function that need them, logging an error if missing.
- Improve error messages when calling tools in PPanGGOLiN, explicitly stating they need to be installed.

Check when external tools are not installed

---

.github/workflows/pypi.yml
ppanggolin/nem/NEM/nem_alg.c
ppanggolin/nem/NEM/nem_exe.c
ppanggolin/nem/NEM/nem_rnd.c
pyproject.toml
setup.py

- The workflow tries to build wheels on every pull request and every push to `dev` branch. The PyPI publishing only runs on release events. 
- It can be triggered manually to test publishing on test.pypi.org.
- Platforms
- macos x86-64/ARM
- linux x86-64 (add `ubuntu-24.04-arm` runner to add Linux ARM support)
- PyPy builds are disabled, we need to check if ppanggolin works on PyPy
- MUSL builds are disabled. NEM does not compile with musl libc but I already have a patch if we want to support it. MUSL is mainly used on Alpine Linux, widely used as a base image for lightweight containers.

Add a workflow for automatic publishing on PyPI

---

ppanggolin/annotate/annotate.py
ppanggolin/utils.py

In this PR (#291), non-ASCII characters have been removed from the **product** field to prevent errors when writing genomic data into the HDF5 file.  
However, similar issues can also occur in the **gene name** field when non-ASCII characters are present, as reported in issues #291 and #252.  
To prevent this, this PR ensures that any non-ASCII characters found in the **name**, **product**, and **dbxref** fields are replaced by an underscore (`_`) character.

 Filter non ASCII character in several annotation fields

---

docs/user/install.md
ppanggolin_env.yaml

This PR does:
- Added instructions for installing PPanGGOLiN from PyPI using pip.
- Removed the default channel from the Conda environment recipe as this channel requires a license and is not necessary for PPanGGOLiN.

Add PyPI install in Documentation

---

docs/user/RGP/rgpOutputs.md

Docs about spot borders had a sentence written in two different ways that meant the same thing litterally. Removing one for clarity.

remove duplicate sentence in borders doc

---

ppanggolin/annotate/annotate.py

This small PR adds an explicit error for cases when the sequence-region pragma in gff3 is poorly formatted, such as in #294.
Since PGAP is heavily used by the community, I'm expecting this kind of errors to happen again in the futur. This should make things easier for users to understand what is wrong.

Raise errors when sequence-region pragma is poorly formatted

---

.github/workflows/main.yml
.github/workflows/pypi.yml
ppanggolin/annotate/annotate.py
ppanggolin/genome.py
ppanggolin/pangenome.py
ppanggolin/workflow/all.py

This PR fixes a bug where contig lengths were required when writing to the HDF5 file, but not yet available if they were missing from the GFF files and only parsed later from FASTA files. This was happening in workflow commands. 
Writing to the HDF5 file, is now called after parsing the FASTA files to ensure contig lengths are available. 
- Triggers PYPI CI  only on master branch PR and push, release and when manually triggered to lower CI load. 
- Adds a concurrency group to the main CI to ensure that only the latest workflow run for a given branch is executed. Any previously queued or in-progress runs will be automatically cancelled when new commits are pushed, saving resources and reducing CI noise.

Fix undefined contig length in workflows

---

ppanggolin/RGP/rgp_cluster.py
ppanggolin/annotate/annotate.py
ppanggolin/formats/writeFlatGenomes.py
ppanggolin/formats/write_proksee.py
ppanggolin/metadata.py

A single element in the pangenome (e.g., a gene family) can have multiple metadata entries from the same source (several PFAM hits).
To store these values in output files (table, gff... ), PPanGGOLiN concatenates them using a separator symbol (default: `"|"`). If any metadata value already contains this symbol, the program raises an error to avoid ambiguity when splitting the values later. Users can provide a custom separator, but:
* This validation is enforced even when there is only **one metadata value**, which is unnecessarily strict and can cause the process to fail for no good reason.
* In the **Proksee map JSON output**, multiple values are also stored as a concatenated string, even though JSON natively supports lists.
* The separator check is now only performed when there are …

 Improve metadata handling in output files

---

ppanggolin/annotate/annotate.py

Genes from GFF files that overlap the start and end of a contig have coordinates exceeding the contig length. These genes need to be processed by PPanGGOLiN to split their coordinates into multiple parts that remain within the contig boundaries( eg:  `[(1041794, 1042393), (1, 1176)]` )
This correction is handled by the `correct_putative_overlaps` function, which updates the `coordinate` attribute of a gene. However, it was not also updating the gene’s `start` and `stop` attributes, leading to inconsistent data.
This PR fixes the issue by ensuring that both the `start` and `stop` attributes are properly updated alongside the `coordinate` attribute.
Thanks @ggautreau for reporting this bug.

Fix gene coordinate update in `correct_putative_overlaps`

---

ppanggolin/__init__.py

Add `__version__` attribute to ppanggolin module to get the version in a standardized way:
```python
import ppanggolin
print(ppanggolin.__version__)
```

Add `__version__` to ppanggolin module to comply with standard

---

.github/workflows/main.yml
README.md
docs/index.md

- Makes CI badge reports the status of the master branch as it matches better user expectation. 
- Fix the badge in the README.md that was missed by PR #355 
- make the CI run on master branch after any push event to have a status to report on this branch
- Replace the 'build' label of the badge by 'CI': [![Actions](https://img.shields.io/github/actions/workflow/status/labgem/PPanGGOLiN/main.yml?branch=master&label=build&logo=github)](https://github.com/labgem/PPanGGOLiN/actions/workflows/main.yml) ➡️ [![Actions](https://img.shields.io/github/actions/workflow/status/labgem/PPanGGOLiN/main.yml?branch=master&label=CI&logo=github)](https://github.com/labgem/PPanGGOLiN/actions/workflows/main.yml)

Make CI badge follows the master branch
